# Generated by Django 5.2.15 on 2026-08-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('published_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('text', models.TextField()),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Mixed', 'Mixed'), ('Neutral', 'Neutral')], default='Neutral', max_length=20)),
                ('issue', models.CharField(choices=[('Affordability', 'Affordability'), ('Safety & Quality', 'Safety & Quality'), ('Accessibility', 'Accessibility'), ('Resource Allocation', 'Resource Allocation'), ('General', 'General')], default='General', max_length=50)),
                ('why', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='policies.policy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
