# Generated by Django 5.2.15 on 2026-08-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
